project:
  type: website
  output-dir: docs
execute:
  freeze: auto
format: html
brand: true
website:
  site-url: "https://smpdl.github.io/jsPsych-Dashboard/" 
  navbar:
    logo: medium
    search: false
    tools:
      - icon: github
        href: "https://github.com/jspsych/jsPsych" 
    left:
      - text: "Home"
        href: index.qmd
      - text: "Pull Requests"
        href: pull_req.qmd
      - text: "Issues"
        href: issues.qmd
      - text: "Discussions"
        href: discussions.qmd  